OPENSCAD=/Applications/OpenSCAD.app/Contents/MacOS/OpenSCAD

default : usage

usage :
	@echo "Usage:"
	@echo "  make all"

all : serenity_model.stl

serenity_model.stl :
	wget http://www.thingiverse.com/download:37338 -O serenity_model.stl


